// <auto-generated />
namespace NaptaWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class onss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onss));
        
        string IMigrationMetadata.Id
        {
            get { return "202206091921216_onss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
